# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f408c7469c4af6b8520f2fd06836667bcedfac355d80d0c10c2fe0e52dbd26b173d496b8805813f2e42405ed0a939a7a0575fb8bbfbb43f8dfe596857b869421

test:
  secret_key_base: 351e19e088c93d18c1f82f04aace87f619019009f0ebcb75536879963070d6c36290b4a3c46dc69de225440a130bd2cdbbc1b42923d028916f8fea98129ed9a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
